TrackerProject/TrackerApp/urls.py
from django.conf.urls import url
from TrackerApp import views

app_name ='TrackerApp'

urlpatterns= [
    url(r'^group_create', views.GroupCreate.as_view(),name='group_create'),
    url(r'^group_detail/(?P<pk>[-\w]+)/$', views.GroupDetail.as_view(),name='group_detail'),
    url(r'^group_update/(?P<pk>[-\w]+)/$', views.GroupUpdate.as_view(),name='group_update'),
    url(r'^member_create/(?P<slug>[-\w]+)/$', views.MemberCreate.as_view(),name='member_create'),
    url(r'^member_detail/(?P<pk>[-\w]+)/$', views.MemberDetail.as_view(),name='member_detail'),
    url(r'^member_update/(?P<pk>[-\w]+)/$', views.MemberUpdate.as_view(),name='member_update'),
    url(r'^practice_create/(?P<slug>[a-zA-Z0-9-]+)/$', views.PracticeCreate.as_view(),name='practice_create'),
    url(r'^practice_detail/(?P<pk>[-\w]+)/$', views.PracticeDetail.as_view(),name='practice_detail'),
    url(r'^practice_update/(?P<pk>[-\w]+)/$', views.PracticeUpdate.as_view(),name='practice_update'),
    url(r'^activity_create', views.ActivityCreate.as_view(),name='activity_create'),
    url(r'^activity_detail/(?P<pk>[-\w]+)/$', views.ActivityDetail.as_view(), name='activity_detail'),
    url(r'^activity_update/(?P<pk>[-\w]+)/$', views.ActivityUpdate.as_view(), name='activity_update'),
]

api_patterns = [

]

urlpatterns += api_patterns

TrackerProject/TrackerProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from TrackerApp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    views.activate, name='activate'),
    url(r'^tracker/',include('TrackerApp.urls',namespace='TrackerApp')),
    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^profile/$', views.user_profile,name='profile'),


]

TrackerProject/TrackerApp/models.py
from django.db import models
import datetime, requests

from django.core import validators
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse

from django.db.models.signals import post_save

from django.dispatch import receiver
from django.contrib.auth.models import User

# Create your models here.
class Coach(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)

    @receiver(post_save, sender=User)
    def update_user_profile(sender, instance, created, **kwargs):
        if created:
            Coach.objects.create(user=instance)
        instance.coach.save()

    def __str__(self):
        return self.user.username

class Group(models.Model):
    name = models.CharField(max_length = 32)
    description = models.TextField()
    coaches = models.ManyToManyField(Coach)
    members = models.ManyToManyField('Member',blank = True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("profile")


class Member(models.Model):
    first_name = models.CharField(max_length = 32)
    last_name = models.CharField(max_length = 32)
    birth_date = models.DateField(max_length = 32)

    def __str__(self):
        return self.last_name+", "+self.first_name

    def get_absolute_url(self):
        return reverse("profile")
        # return reverse("TrackerApp:group_detail")

class Practice(models.Model):
    name = models.CharField(max_length = 32)
    description = models.TextField()
    date = models.DateField()
    attendance = models.ManyToManyField(Member,blank = True)
    group = models.ForeignKey(Group)

    def __str__(self):
        return self.name+str(self.date)

    def get_absolute_url(self):
        return reverse("profile")
        # return reverse("TrackerApp:group_detail")

class ActivityNumber(models.Model):
    activity = models.ForeignKey('Activity')
    amount = models.IntegerField()
    practice = models.ForeignKey(Practice)

    def __str__(self):
        return str(self.practice.date)+": "+self.activity.name+" ("+str(self.amount)+")"

    def get_absolute_url(self):
        return reverse("profile")
        # return reverse("TrackerApp:group_detail")

class Activity(models.Model):
    name = models.CharField(max_length = 32)
    description = models.TextField()
    group = models.ForeignKey(Group)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("profile")
        # return reverse("TrackerApp:group_detail")

TrackerProject/TrackerApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.conf import settings
from snowpenguin.django.recaptcha2.fields import ReCaptchaField
from snowpenguin.django.recaptcha2.widgets import ReCaptchaWidget

import os
from TrackerApp import models


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    # captcha = ReCaptchaField(widget=ReCaptchaWidget())

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)
        widgets = {
            # 'username': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'UserName'}),
            'first_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'}),
        }


class GroupCreateForm(forms.ModelForm):
    model = models.Group
    widgets = {
        'name': forms.TextInput(),
        'description': forms.TextInput(),
    }

    help_texts = {
        'name': ("Name of the Group"),
        'description': ("Description of group"),
    }

class ActivityCreateForm(forms.ModelForm):
    class Meta:
        model = models.Activity
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(),
            'description': forms.TextInput(),
            # forms.ChoiceField(widget= forms.Select(attrs={'class': 'form-control'})),
        }

        help_texts = {
            'name': ("Name of the Activity"),
            'description': ("Description of the activity"),
        }

TrackerProject/TrackerApp/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView, CreateView, DeleteView, UpdateView, DetailView)
from TrackerApp import models, forms, tokens
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect
# Create your views here.
#home page
class IndexView(TemplateView):
    template_name = 'TrackerApp/index.html'


class CoachDetailView(DetailView):
    model = models.Coach
    fields = '__all__'
    template_name = 'TrackerApp/coach_detail.html'

def user_profile(request):
    user_groups = None
    template_name = 'TrackerApp/coach_detail.html'
    if request.user.is_authenticated():
        user_groups = models.Group.objects.filter(coaches__user = request.user)
        context = {
            'user_groups':user_groups,
        }
    else:
        context = None
    return render(request,template_name,context)

class GroupCreate(CreateView):
    model = models.Group
    fields = ['name','description','members','coaches']
    template_name = 'TrackerApp/group_create.html'


class GroupDetail(DetailView):
    model = models.Group
    fields = "__all__"
    template_name = 'TrackerApp/group_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group_members'] = models.Member.objects.filter(group = self.get_object())
        context['group_practices'] = models.Practice.objects.filter(group = self.get_object())
        context['group_activities'] = models.Activity.objects.filter(group = self.get_object())
        context['total_members'] = (len(self.get_object().members.all()))
        context['total_acts'] = len(models.Activity.objects.filter(group = self.get_object()))
        context['total_prac'] = len(models.Practice.objects.filter(group = self.get_object()))
        return context

class GroupUpdate(UpdateView):
    model = models.Group
    fields = "__all__"
    template_name = 'TrackerApp/group_update.html'

class MemberCreate(CreateView):
    model = models.Member
    fields = '__all__'
    template_name = "TrackerApp/member_create.html"

    def form_valid(self, form):
        response = super(MemberCreate, self).form_valid(form)
        group_pk = self.kwargs['slug']
        group = models.Group.objects.get(pk = group_pk)
        group.members.add(self.object)
        group.save()
        return response


class MemberDetail(DetailView):
    model = models.Member
    fields = '__all__'
    template_name = "TrackerApp/member_detail.html"

# groups apart of
#activities they have participated
#filter by week,month, two months
#attendence rate for each Groups
#upcoming practices?
#field to keep notes on player?

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # get all groups
            # for each group get all practices with user in attendance
                # for each practice add to total sum of each activity in dict amount
        context["Group_Stats"] = dict()
        for group in self.object.group_set.all():
            context["Group_Stats"][group.pk]= dict()
            context["Group_Stats"][group.pk]["name"] = dict()
            context["Group_Stats"][group.pk]["attendance"] = dict()
            context["Group_Stats"][group.pk]["activity_totals"]=dict()
            for group_practice in group.practice_set.all():
                print(group_practice)
                for activity_num in group_practice.activitynumber_set.all():
                    print(activity_num)
                    context["Group_Stats"][group.pk]["name"] = group.name
                    context["Group_Stats"][group.pk]["attendance"] = len(models.Practice.objects.filter(group__pk = group.pk).filter(attendance__id = self.object.pk))
                    context["Group_Stats"][group.pk]["total_practices"] = len(models.Practice.objects.filter(group__pk = group.pk))
                    if not activity_num.activity.pk in context["Group_Stats"][group.pk]["activity_totals"].keys():
                        context["Group_Stats"][group.pk]["activity_totals"][activity_num.activity.pk]=dict()

                    if not "name" in context["Group_Stats"][group.pk]["activity_totals"][activity_num.activity.pk].keys():
                        context["Group_Stats"][group.pk]["activity_totals"][activity_num.activity.pk]["name"] = dict()

                    context["Group_Stats"][group.pk]["activity_totals"][activity_num.activity.pk]["name"] = activity_num.activity.name
                    if "total" in context["Group_Stats"][group.pk]["activity_totals"][activity_num.activity.pk].keys():
                        print("Adding in "+str(activity_num.amount)+" from "+activity_num.activity.name)
                        context["Group_Stats"][group.pk]["activity_totals"][activity_num.activity.pk]["total"]+= activity_num.amount
                    else:
                        context["Group_Stats"][group.pk]["activity_totals"][activity_num.activity.pk]["total"] = dict()
                        context["Group_Stats"][group.pk]["activity_totals"][activity_num.activity.pk]["total"] = activity_num.amount
        print(context)
        return context

class MemberUpdate(UpdateView):
    model = models.Group
    fields = '__all__'
    template_name = 'TrackerApp/member_update.html'

class PracticeCreate(CreateView):
    model = models.Practice
    fields = ['name', 'description', 'date', 'attendance', "group"]
    template_name = 'TrackerApp/practice_create.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        activity_numbers = models.ActivityNumber.objects.filter(practice__group__pk = self.kwargs['slug'])
        context["activity_totals"] = dict()
        for act_num in activity_numbers:
            context["activity_totals"][act_num.activity.pk]= dict()
            context["activity_totals"][act_num.activity.pk]["name"]=dict()
            context["activity_totals"][act_num.activity.pk]["total"] = dict()

        for act_num in activity_numbers:
            context["activity_totals"][act_num.activity.pk]["name"]=act_num.activity.name
            if context["activity_totals"][act_num.activity.pk]["total"]:
                context["activity_totals"][act_num.activity.pk]["total"]+=act_num.amount
            else:
                context["activity_totals"][act_num.activity.pk]["total"] = act_num.amount
        context["activities"]=models.Activity.objects.filter(group__pk = self.kwargs['slug'])
        print(context)
        return context

    def get_success_url(self, **kwargs):
         group_activities = models.Activity.objects.filter(group__pk = self.kwargs['slug'])
         for activity in group_activities:
             activity_amount= self.request.POST.get(str(activity.pk))
             models.ActivityNumber.objects.create(activity = activity, amount=activity_amount, practice = self.object)

         return super().get_success_url()

class PracticeDetail(DetailView):
    model = models.Practice
    fields = '__all__'
    template_name = 'TrackerApp/practice_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group_size = len(self.get_object().group.members.all())
        if (group_size):
            context['attendance_rate'] = (len(self.get_object().attendance.all())/group_size) * 100
        return context

class PracticeUpdate(UpdateView):
    model = models.Practice
    fields = '__all__'
    template_name = 'TrackerApp/practice_update.html'

class ActivityCreate(CreateView):
    model = models.Activity
    fields = '__all__'
    template_name = 'TrackerApp/activity_create.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context

class ActivityDetail(DetailView):
    model = models.Activity
    fields = '__all__'
    template_name = 'TrackerApp/activity_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        activity_numbers = models.ActivityNumber.objects.filter(activity = self.kwargs['pk'])
        act_amount =0

        for act_num in activity_numbers:
            act_amount += act_num.amount
            context['activity_amount'] =act_amount

        return context

    # last time activity was completed
    # numbers of times completed in past month

class ActivityUpdate(UpdateView):
    model = models.Activity
    fields = '__all__'
    template_name = 'TrackerApp/activity_update.html'

#users signs up for a profile
def signup(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.save()
            current_site = get_current_site(request)

            #send user registration email with activation link
            # message = render_to_string('registration/acc_active_email.html', {
            #     'user':user,
            #     'domain':current_site.domain,
            #     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token': tokens.account_activation_token.make_token(user),
            # })
            # mail_subject = 'Activate your Group Tracker account.'
            # to_email = form.cleaned_data.get('email')
            # subject = "Group Tracker Account Activation"
            # email = EmailMessage(subject, message, to=[to_email])
            # email.send()
            return render(request, 'TrackerApp/index.html')
    else:
        form = forms.SignUpForm()

TrackerProject/templates/TrackerApp/activity_create.html
<div class="form-group row">
  {% extends 'base.html' %}
  {% block body_block %}
  <title>Create Activity</title>
<form method="post">
{%if not form.instance.pk%}
  <h1>Submit An Activity</h1>
  {% csrf_token %}

  {%else%}
  <h1>Update Your Activity</h1>
  {%endif%}

  {% for field in form %}
    {%if not request.user.is_authenticated%}
      Log in or register to be able to save your submissions and keep them private
    {%else%}
      {{ field.label_tag }} {{field}}
      {{field.errors}}
    {%endif%}
  {% endfor %}
  <button type="submit">Create</button>
</form>

{%endblock%}

TrackerProject/templates/TrackerApp/activity_detail.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Activity Overview</h1>
<p>Name: {{activity.name}}</p>
<p>Descripton: {{activity.description}}</p>
<p>Total Number Completed: {{activity_amount}}</p>
<a href="{% url 'TrackerApp:activity_update' activity.pk%}">Edit Activity</a>
{% endblock %}

TrackerProject/templates/TrackerApp/activity_update.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Activity Update</h1>
<form class="" method="post">
  <p>{{form.as_p}}</p>
  {%csrf_token%}
  <button type="submit">Create</button>
</form>
{% endblock %}

TrackerProject/templates/TrackerApp/coach_detail.html
{% extends 'base.html' %}
{% block body_block %}
{%if user.is_authenticated%}
<h1>Coach {{user.get_username}}'s Profile<h1>

  <h2>Your Groups</h2>
  {% if user.groups %}
	 <div class="list-group">
	{%for group in user_groups%}
		<a href="{%url 'TrackerApp:group_detail' group.pk%}" class="list-group-item" >{{group.name}}</a>

	{%endfor%}
  </div>
   {% else %}
   <p> No groups </p>
   {% endif %}
  <h3><a class="btn btn-primary btn-lg" href="{%url 'TrackerApp:group_create' %}">Add New Groups</a></h3>
  {%else%}
  <h1> You are not logged in. Please log in to view this page.</h1>
 {%endif%}

{% endblock %}

TrackerProject/templates/TrackerApp/group_create.html
{% extends 'base.html' %}

{%block headblock%}

{%endblock%}


{% block body_block %}
<title>Create Group</title>
<h1>Group Create</h1>
<form  method="post">
  {{form.as_table}}
  {%csrf_token%}
  <button type="submit">Create</button>
</form>

{% endblock %}

TrackerProject/templates/TrackerApp/group_detail.html
{% extends 'base.html' %}
{%block headblock%}
<script type="text/javascript">
window.onload = function () {
	var chart = new CanvasJS.Chart("chartContainer",
	{
		title:{
			text: "Overview"
		},
		legend: {
			//interval: 5,
			maxWidth: 350,
			itemWidth: 120
		},
		data: [
		{
			type: "bar",
			//showInLegend: true,
		//	legendText: "{indexLabel}",
			dataPoints: [
				{ y: {{total_prac}}, label: "Practices" },
				{ y: {{total_acts}}, label: "Activities" },
				{y: {{total_members}}, label: "Members", }
			]
		}
		]
	});
	chart.render();
}
</script>
<script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
{%endblock%}
{% block body_block %}

<h1>{{group.name}}</h1>
<p>{{group.description}}</p>
<a class="btn btn-primary btn-lg" href="{% url 'TrackerApp:group_update' group.pk%}">Edit Group Details</a>
<p></p>
<h2>Group Members</h2>
 <div class="list-group">
{%for member in group_members%}

	<a class="list-group-item" href="{% url 'TrackerApp:member_detail' member.pk%}">{{member.last_name}}, {{member.first_name}}</a>
{%endfor%}
</div>
<a class="btn btn-primary btn-lg" href="{% url 'TrackerApp:member_create' group.pk%}">Add Members</a>
<p></p>

<h2>Group Practice</h2>
<div  class="list-group">
	{%for practice in group_practices%}
		<a class="list-group-item" href="{% url 'TrackerApp:practice_detail' practice.pk%}">{{practice.name}}</a>
	{%endfor%}
</div>
<a class="btn btn-primary btn-lg" href="{% url 'TrackerApp:practice_create' group.pk%}">Add Practice</a>
<p></p>

<h2>Group Activities</h2>
 <div class="list-group">
{%for activity in group_activities%}
	<a class="list-group-item" href="{% url 'TrackerApp:activity_detail' activity.pk%}">{{activity.name}}</a>
{%endfor%}
</div>

<a  class="btn btn-primary btn-lg" href="{% url 'TrackerApp:activity_create'%}">Add Activity</a>
<p></p>
<p style="position: absolute; top: 75px; left: 500px;">Number of Members: {{total_members}}</p>
<p style="position: absolute; top: 95px; left: 500px;">Number of Practices: {{total_prac}}</p>
<p style="position: absolute; top: 115px; left: 500px;">Number of Activities: {{total_acts}}</p>

<div id="chartContainer" style="position: absolute; top: 50px; left: 700px; height: 200px; width: 40%;"></div>

{% endblock %}

TrackerProject/templates/TrackerApp/group_update.html
{% extends 'base.html' %}
{% block head_block %}

{% endblock %}
{% block body_block %}
<h1>Group Update</h1>
<form class="" method="post">
  <p>{{form.as_p}}</p>
  {%csrf_token%}
  <button type="submit">Update</button>
</form>



{% endblock %}

TrackerProject/templates/TrackerApp/index.html
{% extends 'base.html' %}

{% block body_block %}

  <div class="jumbotron">
    <h1>Training Tracker</h1>
    <p>Training Tracker is the best way to keep track of your organization's members and their routines.</p>
	<div class="row">
		{%if user.is_authenticated%}
		<div class="col-lg-2 col-md-6 col-sm-6">
            <p><a class="btn btn-primary btn-lg" href="{% url 'profile'%}" role="button">View Your Profile</a> </p>
          </div>
		{%else%}
          <div class="col-lg-2 col-lg-offset-4 col-md-offset-4 col-md-2 col-sm-offset-3 col-sm-3 col-xs-offset-3 col-xs-3">
            <p><a class="btn btn-success btn-lg" href="{% url 'signup'%}" role="button">Get Started</a> </p>
          </div>
		{%endif%}
		  
    </div>
</div>
{%if user.is_authenticated %}

{% else%}
<small> Already have an account? <a href="{%url 'login'%}"> Log In here.</a>
{%endif%} 
<div class="page-header">
  <h1>About Us</h1>
  Training Tracker offers a way to keep track of your organization's members. When you sign up, you can create groups for the organizations you manage, add members to the groups, define group activities and log statistics about your members and the activities they participate in.
</div>
</div>
{% endblock %}

TrackerProject/templates/TrackerApp/member_create.html
{% extends 'base.html' %}

{% block body_block %}
  <h1>Create A New Member</h1>
  <form method="post">
      {{ form.as_p }}
      {%csrf_token%}
      <input type="hidden" name="slug" value="{{instance.slug}}">
    <button type="submit">Create!</button>
  </form>
{% endblock %}

TrackerProject/templates/TrackerApp/member_detail.html
{% extends 'base.html' %}
{%block headblock%}
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
{%for key,group in Group_Stats.items%}
<script>

window.onload = function () {

var barchart{{key}} = new CanvasJS.Chart("chartContainer{{key}}", {
	animationEnabled: true,
	theme: "light2", // "light1", "light2", "dark1", "dark2"
	title:{
		text: " {{member.first_name}}'s {{group.name}} Activity History"
	},
	axisY: {
		title: "Repititions"
	},
	data: [{
		type: "column",
		showInLegend: true,
		legendMarkerColor: "grey",
		dataPoints: [
			{%for key,activity_sums in group.items%}
				{%for key, sum in activity_sums.items%}
					{ y:{{sum.total}} , label: "{{sum.name}}" },
				{%endfor%}
			{%endfor%}
		]
	}]
});
	var piechart{{key}} = new CanvasJS.Chart("attendance{{key}}",
	{
		title:{
			text: "Attendance"
		},
		legend: {
			maxWidth: 350,
			itemWidth: 120
		},
		data: [
		{
			type: "pie",
			showInLegend: true,
			legendText: "{indexLabel}",
			dataPoints: [
				{ y: {{group.attendance}}, indexLabel: "Present" },
				{ y: {{group.total_practices}} - {{group.attendance}}, indexLabel: "Absent" }
			]
		}
		]
	});
	piechart{{key}}.render();
	barchart{{key}}.render();
}
</script>
<script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
{%endfor%}
{%endblock%}
{% block body_block %}
<h1>Member Overview</h1>
<p>Name: {{member.last_name}}, {{member.first_name}} </p>
<p>Date of Birth: {{member.birth_date}}</p>

{%for key,group in Group_Stats.items%}
  <p>Group Name: {{group.name}}</p>
  {%for key,activity_sums in group.items%}
    {%for key, sum in activity_sums.items%}
      <p>{{sum.name}}:{{sum.total}}</p>
    {%endfor%}
  {%endfor%}
	<div id="chartContainer{{key}}" style="height: 370px; width: 100%;"></div>
	<div id="attendance{{key}}"  top: 50px; left: 500px; height: 400px; width: 70%;"></div>
{%endfor%}


<a href="{% url 'TrackerApp:member_update' member.pk%}">Edit Member</a>


{% endblock %}

TrackerProject/templates/TrackerApp/member_update.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Member Update</h1>
<form class="" method="post">
  <p>{{form.as_p}}</p>
  {%csrf_token%}
  <button type="submit">Update</button>
</form>

{% endblock %}

TrackerProject/templates/TrackerApp/practice_create.html
{% extends 'base.html' %}
{%block headblock%}
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	theme: "light2", // "light1", "light2", "dark1", "dark2"
	title:{
		text: "Group Activity History"
	},
	axisY: {
		title: "Repititions"
	},
	data: [{
		type: "column",
		showInLegend: true,
		legendMarkerColor: "grey",
		dataPoints: [
      {%for key,act_tot in activity_totals.items%}
			{ y:{{act_tot.total}} , label: "{{act_tot.name}}" },
      {%endfor%}
		]
	}]
});
chart.render();

}
</script>
{%endblock%}
{% block body_block %}
  <title>Create Practice</title>

  <h1>Practice History</h1>
  <div id="chartContainer" style="height: 370px; width: 100%;"></div>
  <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

  <h1>Create New Practices</h1>
  <form method="post">
      {{ form.as_p }}
      {%csrf_token%}

      {%for activity in activities%}
        <p>{{activity.name}}: <input type="number" name="{{activity.pk}}" value=""></p>
      {%endfor%}

    <button type="submit">Create!</button>
  </form>

{% endblock %}

TrackerProject/templates/TrackerApp/practice_detail.html
{% extends 'base.html' %}
{%block headblock%}
<script type="text/javascript">
window.onload = function () {
	var chart = new CanvasJS.Chart("chartContainer",
	{
		title:{
			text: "Attendance"
		},
		legend: {
			maxWidth: 350,
			itemWidth: 120
		},
		data: [
		{
			type: "pie",
			showInLegend: true,
			legendText: "{indexLabel}",
			dataPoints: [
				{ y: {{attendance_rate}}, indexLabel: "Present" },
				{ y: 100 - {{attendance_rate}}, indexLabel: "Absent" }
			]
		}
		]
	});
	chart.render();
}
</script>
<script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
{%endblock%}
{% block body_block %}
<h1>Practices Overview</h1>
<p>{{practice.name}}</p>
<p>{{practice.description}}</p>

<h4>Members Attended:</h4>
{%for member in practice.attendance.all%}
<p>{{member.last_name}},{{member.first_name}}</p>
{%endfor%}

<h4>Activites Performed:</h4>
{%for act_num in practice.activitynumber_set.all%}
<p>{{act_num.activity.name}}:{{act_num.amount}}</p>
{%endfor%}
<div id="chartContainer" style="position: absolute; top: 50px; left: 500px; height: 400px; width: 70%;"></div>
<a href="{% url 'TrackerApp:practice_update' practice.pk%}">Edit Practice</a>
<p style="position: absolute; top: 100px; left: 575px;">Attendance Rate: {{attendance_rate}} %</p>
{% endblock %}

TrackerProject/templates/TrackerApp/practice_update.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Practice Edit</h1>
<div>
<form class=""  method="post">
  <p>{{form.as_p}}</p>
  {%csrf_token%}
  <button type="submit">Update</button>
  </div>
</form>

{% endblock %}